/**
 * Ory Kratos
 * Welcome to the ORY Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Identity } from './identity';

export class Session {
    'authenticatedAt'?: Date;
    'expiresAt'?: Date;
    'identity'?: Identity;
    'issuedAt'?: Date;
    'sid'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authenticatedAt",
            "baseName": "authenticated_at",
            "type": "Date"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date"
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "Identity"
        },
        {
            "name": "issuedAt",
            "baseName": "issued_at",
            "type": "Date"
        },
        {
            "name": "sid",
            "baseName": "sid",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Session.attributeTypeMap;
    }
}

