apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"admin-api","namespace":"scansure"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"admin-api"}},"template":{"metadata":{"labels":{"app":"admin-api"}},"spec":{"containers":[{"command":["/bin/sh","-c","while true; do sleep 30; done"],"image":"alpine:latest","name":"admin-api","volumeMounts":[{"mountPath":"/mnt/secrets-store","name":"secrets-store","readOnly":true}]}],"volumes":[{"csi":{"driver":"secrets-store.csi.k8s.io","readOnly":true,"volumeAttributes":{"secretProviderClass":"scansure-vault-spc"}},"name":"secrets-store"}]}}}}
  creationTimestamp: "2025-11-03T05:10:26Z"
  generation: 2
  name: admin-api
  namespace: scansure
  resourceVersion: "125696"
  uid: 56082592-136c-44d1-bcfa-00774d00835e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: admin-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-03T17:25:35+05:30"
      labels:
        app: admin-api
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do sleep 30; done
        image: alpine:latest
        imagePullPolicy: Always
        name: admin-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: scansure-vault-spc
        name: secrets-store
status:
  conditions:
  - lastTransitionTime: "2025-11-03T12:16:10Z"
    lastUpdateTime: "2025-11-03T12:16:10Z"
    message: ReplicaSet "admin-api-6dd96d4597" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  - lastTransitionTime: "2025-11-04T04:40:51Z"
    lastUpdateTime: "2025-11-04T04:40:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
