/**
 * Ory Kratos
 * Welcome to the ORY Kratos HTTP API documentation!
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CompleteSelfServiceBrowserProfileManagementFlowPayload {
    /**
    * Traits contains all of the identity\'s traits.  type: string format: binary
    */
    'traits': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "traits",
            "baseName": "traits",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return CompleteSelfServiceBrowserProfileManagementFlowPayload.attributeTypeMap;
    }
}

